### ISSUE TITLE
Дублирование кода

### ISSUE THREAD

**Issue by sergey-shambir** [eligantRU/eligant.ru#38]
Функция initAssets постоянно совершает одни и те же действия

``` cpp
if (!game.assets.ROCKET_NONE_TEXTURE.loadFromFile("images/Rocket_none_23_36.png"))
{
    printf("Error loaded file");
}
game.assets.ROCKET_NONE_TEXTURE.setSmooth(true);
```

Следует вынести это действие в функцию либо в лямбду, и вызвать её множество раз с разными аргументами.

**Comment by eligantRU** [comment]
Устранено
