### ISSUE TITLE
Абстрагирование сцены

### ISSUE THREAD

**Issue by sergey-shambir** [eligantRU/eligant.ru#39]
Сейчас игра имеет несколько разных сцен, каждая из которых имеет свой
- внешний вид
- данные
- поведение

Каждая сцена реализована как одна или несколько функций, каждая функция внутри крутит свой цикл событий SFML и дублирует код, но дублирует не полностью, что вызывает баги из разряда "Не работает Alt+F4".

Цикл событий должен быть более универсальным. А для этого следует абстрагироваться от сцен.

Сперва выделим, какие сцены существуют в данный момент. Я вижу следующее:
1. onPauseMenu
2. onStartMenu
3. onGameOverMenu
4. enterGameLoop, gameLoop, update, resetGame, initAssets

**Comment by sergey-shambir** [comment]
Этап первый: создать новые пары файлов h/cpp и переместить туда объявления и определения функций:
- onPauseMenu: в файл PauseScene h/cpp
- onStartMenu: в файл StartScene h/cpp
- onGameOverMenu: в файл GameOverScene h/cpp
- enterGameLoop, gameLoop, update, resetGame, initAssets в файл GameScene h/cpp
  Это изменение пригодится для следующих этапов.

**Comment by sergey-shambir** [comment]
Этап второй: в каждом файле сцены основную функцию (onPauseMenu, enterGameLoop, ...) отрефакторить так, чтобы был чётко видны шаги: инициализация, основной цикл событий, разрушение. В итерации цикла событий должны быть чётко видны шаги: обработка события игры, обновление состояния игры, рисование. Псевдокод:

``` cpp
// init step
initAssets(gameScene);
resetGame(gameScene, view);
// loop
while (window.isOpen())
{
    game.frameFunc(window);
}
// scope exit is destroy step
```

Функция enterGameLoop уже близка к такому состоянию, только надо подфункцию gameLoop вернуть обратно внутрь enterGameLoop, чтобы цикл был виден прямо в enterGameLoop.

**Comment by eligantRU** [comment]
Хотя есть определённые претензии, в целом -- сделано
