### ISSUE TITLE
Замечания по стилю кодирования

### ISSUE THREAD

**Issue by eligantRU** [eligantRU/eligant.ru#43]
- Имя типа с большой буквы в CamelCase нотации
- Использовать списки инициализации в конструкторе
- вместо NULL надо использовать nullptr.
- в конструктор передавать по ссылке, а не по указателю

**Comment by eligantRU** [comment]
- Реализовать addRepeatedTexture вместо дефолтного булевского параметра

**Comment by sergey-shambir** [comment]
Можно закрывать
