### ISSUE TITLE
Добавить корректную поддержку клавиатуры

### ISSUE THREAD

**Issue by eligantRU** [eligantRU/eligant.ru#44]
- Ловить событие keyPressed и keyReleased
- Далее, при нажатии A устанавливать булевское поле, а при отжатии -- снимать. Аналогично для D
- После любого изменения поля вызывать метод updateDirection()
- В методе updateDirection() проверять состояние булевских полей и выбирать направление для Дудла
- У Дудла убрать поле lastDirection, но добавить setDirection(). Поле Direction сделать приватным
- В методе setDirection() не только устанавливать Direction, но и обновлять спрайт

**Comment by sergey-shambir** [comment]
Можно закрывать
