### ISSUE TITLE
Устранить предупреждения компилятора и поправить настройки

### ISSUE THREAD

**Issue by sergey-shambir** [eligantRU/eligant.ru#46]
### Предупреждения
- выставить уровень W4
- пересобрать проект
- устранить предупреждения
- все включения SFML переместить в stdafx.h

Чтобы при компиляции SFML не вылезали предупреждения, надо с помощью специфичных для Visual C++ прагм временно снизить уровень предупреждений до 3

``` cpp
#pragma warning (push, 3)
// Include SFML here
#pragma warning (pop)
```
### Абсолютные пути в проекте

Надо открыть Property Manager (можно включить через меню View->Property Manager) и там в локальном property sheet "Microsoft.Cpp.Win32.user" поместить все пути поиска SFML (include и lib)

**Comment by sergey-shambir** [comment]
Предупреждение насчёт `font` не устранено.

**Comment by sergey-shambir** [comment]
Проверить в VS2015 Update 2.

**Comment by eligantRU** [comment]
- Предупреждение насчёт font устранено
- Студия обновлена до Update 2
- Прикрутил Debug compiler configuration (до этого всё делалось исключительно в Release)
