### ISSUE TITLE
Мелкие замечания

### ISSUE THREAD

**Issue by sergey-shambir** [eligantRU/eligant.ru#47]
- в структуре Button убрать публичные поля и нереализованный метод
- в структурах Bonus, Doodle, Plate убрать публичные поля

**Comment by sergey-shambir** [comment]
строку в getStringLengthPx надо передавать по константной ссылке, после закрыть

**Comment by sergey-shambir** [comment]
- float Button::getStringLengthPx(const std::string str)
  это не константная ссылка, а константный параметр.
- `setText(std::string text)` тоже по константной ссылке
- в конструктор Button тоже по константной ссылке
- Button::m_body создаётся через new и не удаляется

**Comment by sergey-shambir** [comment]
Переименовать в классе Assets `font` в `ARIAL_FONT`

**Comment by eligantRU** [comment]
- Assets::font переименован в ARIAL_FONT
- Устранены замечания по константным ссылкам для getStringLengthPx() и setText()
- Button::m_body удаляется при вызове деструктора
