### ISSUE TITLE
Внедрение умных указателей.

### ISSUE THREAD

**Issue by sergey-shambir** [eligantRU/eligant.ru#48]
- умные указатели всё-таки надо внедрить. Для большинства ситуаций подойдёт std::unique_ptr. Перед этим желательно сделать поле приватным, чтобы кто-то снаружи не пытался его удалить.

**Comment by sergey-shambir** [comment]
Поскольку сцены не удаляются, то и умные указатели фактически не используются. Следует исправить удаление сцен.

**Comment by sergey-shambir** [comment]
`Assets` следует везде захватывать по ссылке, а не класть в unique_ptr.

**Comment by sergey-shambir** [comment]
Вообще не катет

``` cpp
*m_plates = nullptr;
*m_bonuses = nullptr;
```

**Comment by eligantRU** [comment]
Assets захватываю по ссылке, в smart pointer более не заталкиваю
Аналогично для sf::View(вечный спутник, так сказать)
Ошибка, связанная с кучей, устранена.

Деструкторы исправлены: более нет никаких бесполезных действий по об'nullptr'иванию smart-pointer'ов
