### ISSUE TITLE
Чистка кода

### ISSUE THREAD

**Issue by sergey-shambir** [eligantRU/eligant.ru#52]
- метод GameScene::generPlates не хочет помещаться в один экран
- метод `uint64_t getScore(void);` должен быть константным
- функции не должны принимать `(void)`, список аргументов в таких случаях должен быть пустым.
- удалить `SDirection`
- к классе Assets не должно быть изменяемой переменной типа `sf::Sound`
- в классе Bonus методы должны быть константными

Более абстрактно: все методы, не изменяющие состояние объекта, должны быть константными, если только иного не требует спецификация интерфейса, от которого наследуется класс.

**Comment by eligantRU** [comment]
В целом -- замечание устранено, за исключением GameScene::generPlates
На эту тему сейчас открою новый issue: вся GameScene подлежит жёсткому рефакторингу, возможно, разбиению на несколько файлов, да и вообще там несколько методов нужно обновить

**Comment by eligantRU** [comment]
GameScene::generPlates полностью переписан под новую логику. Теперь умещается даже на экране смартфона в альбомной ориентации :)
Все описанные выше замечания устранены
